// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQrA29lvgsb0WyAmHE9gzIpr9D5e_sRQM',
    appId: '1:826569933105:web:ea4db47c2a6f407bc53010',
    messagingSenderId: '826569933105',
    projectId: 'mindflow-a55fe',
    authDomain: 'mindflow-a55fe.firebaseapp.com',
    storageBucket: 'mindflow-a55fe.firebasestorage.app',
    measurementId: 'G-GMYNZRW9RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdoWrpFt7Aa81HBBOQYA-hw7gBYYY2d0o',
    appId: '1:826569933105:android:a399254371aa8c5ec53010',
    messagingSenderId: '826569933105',
    projectId: 'mindflow-a55fe',
    storageBucket: 'mindflow-a55fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbJlGS11vdIT-qCETgIGmfCW7o9qEXHK0',
    appId: '1:826569933105:ios:b4997b2e0a5138e1c53010',
    messagingSenderId: '826569933105',
    projectId: 'mindflow-a55fe',
    storageBucket: 'mindflow-a55fe.firebasestorage.app',
    iosBundleId: 'com.example.mindflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbJlGS11vdIT-qCETgIGmfCW7o9qEXHK0',
    appId: '1:826569933105:ios:b4997b2e0a5138e1c53010',
    messagingSenderId: '826569933105',
    projectId: 'mindflow-a55fe',
    storageBucket: 'mindflow-a55fe.firebasestorage.app',
    iosBundleId: 'com.example.mindflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQrA29lvgsb0WyAmHE9gzIpr9D5e_sRQM',
    appId: '1:826569933105:web:c90d02509bbd2156c53010',
    messagingSenderId: '826569933105',
    projectId: 'mindflow-a55fe',
    authDomain: 'mindflow-a55fe.firebaseapp.com',
    storageBucket: 'mindflow-a55fe.firebasestorage.app',
    measurementId: 'G-BY58SL0F6B',
  );

}